### ISSUE TITLE
[Windows] Illegal Key Size

### ISSUE THREAD

**Issue by nxion** [hasherezade/jpassword_scrambler#2]
The `Illegal Key Size` error also seems to popup on Windows 7 with JRE 7. The fix for macOS seems to resolve the error in Windows. I will also test JRE 6 and 8 on never versions of Windows but I assume it would be the same result and the fix would be to add the JCE jars.

Also, this is one of the coolest password managers I have every seen/used. I might drop LastPass for this. Kudos!

**Comment by hasherezade** [comment]
Thanks for the notice. I added it to readme.
And I am so happy that you like the app :smile: ! enjoy
